name: Build Sphinx Pages

on:
  push:
    branches: [1-setup-workflow-for-github-pages, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - run: pip install sphinx

      - run: make html

      - run: mkdir docs || true

      - run: cp -r build/html/* docs/

      - run: touch docs/.nojekyll

      - run: git config --global user.email "epfspencer@yahoo.com"

      - run: git config --global user.name "Edward Spencer"

      - run: git checkout 1-setup-workflow-for-github-pages

      - run: git add --all

      - run: git commit -m 'Update sphinx build'

      - run: git push origin 1-setup-workflow-for-github-pages