name: Build Sphinx Pages

on:
  push:
    branches: [main, 2-setup-graphviz]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # setup dependencies
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - run: pip install sphinx
      - run: sudo apt install graphviz

      # setup git
      - run: git config --global user.email "epfspencer@yahoo.com"
      - run: git config --global user.name "Edward Spencer"

      # force build branch to current head
      - run: git branch -f sphinx-build

      # rebuild the docs
      - run: make html
      - run: if [[ -d docs ]]; then rm -rf docs; fi
      - run: mkdir docs
      - run: cp -r build/html/* docs/
      - run: touch docs/.nojekyll

      # push back updated docs to sphinx-build branch
      - run: git checkout sphinx-build
      - run: git add --all
      - run: git commit -m 'Update sphinx build'
      - run: git push origin sphinx-build --force
